mkdir --parents `dirname dolphin/dolphin._desktop_` && mv applications/dolphin._desktop_.po dolphin/dolphin._desktop_.po
mkdir --parents `dirname dolphin/dolphin_servicemenuinstaller` && mv applications/dolphin_servicemenuinstaller.po dolphin/dolphin_servicemenuinstaller.po
mkdir --parents `dirname dolphin/dolphin` && mv applications/dolphin.po dolphin/dolphin.po
mkdir --parents `dirname kate/kate._json_` && mv applications/kate._json_.po kate/kate._json_.po
mkdir --parents `dirname kate/kate` && mv applications/kate.po kate/kate.po
mkdir --parents `dirname konsole/konsole` && mv applications/konsole.po konsole/konsole.po
mkdir --parents `dirname kfind/kfind` && mv applications/kfind.po kfind/kfind.po
mkdir --parents `dirname drkonqi/drkonqi5` && mv kde-workspace/drkonqi5.po drkonqi/drkonqi5.po
mkdir --parents `dirname discover/org.kde.discover.snap.appdata` && mv kde-workspace/org.kde.discover.snap.appdata.po discover/org.kde.discover.snap.appdata.po
mkdir --parents `dirname plasma-nm/plasma-nm._desktop_` && mv kde-workspace/plasma-nm._desktop_.po plasma-nm/plasma-nm._desktop_.po
mkdir --parents `dirname plasma-nm/plasma_applet_org.kde.plasma.networkmanagement` && mv kde-workspace/plasma_applet_org.kde.plasma.networkmanagement.po plasma-nm/plasma_applet_org.kde.plasma.networkmanagement.po
mkdir --parents `dirname kinfocenter/kinfocenter._desktop_` && mv kde-workspace/kinfocenter._desktop_.po kinfocenter/kinfocenter._desktop_.po
mkdir --parents `dirname discover/plasma-discover-notifier` && mv kde-workspace/plasma-discover-notifier.po discover/plasma-discover-notifier.po
mkdir --parents `dirname discover/org.kde.discover.flatpak.appdata` && mv kde-workspace/org.kde.discover.flatpak.appdata.po discover/org.kde.discover.flatpak.appdata.po
mkdir --parents `dirname plasma-workspace/plasma-workspace._desktop_` && mv kde-workspace/plasma-workspace._desktop_.po plasma-workspace/plasma-workspace._desktop_.po
mkdir --parents `dirname discover/discover._desktop_` && mv kde-workspace/discover._desktop_.po discover/discover._desktop_.po
mkdir --parents `dirname plasma-desktop/plasma_applet_org.kde.desktopcontainment` && mv kde-workspace/plasma_applet_org.kde.desktopcontainment.po plasma-desktop/plasma_applet_org.kde.desktopcontainment.po
mkdir --parents `dirname kinfocenter/kinfocenter` && mv kde-workspace/kinfocenter.po kinfocenter/kinfocenter.po
mkdir --parents `dirname discover/plasma-discover` && mv kde-workspace/plasma-discover.po discover/plasma-discover.po
mkdir --parents `dirname discover/org.kde.discover.appdata` && mv kde-workspace/org.kde.discover.appdata.po discover/org.kde.discover.appdata.po
mkdir --parents `dirname discover/org.kde.discover.packagekit.appdata` && mv kde-workspace/org.kde.discover.packagekit.appdata.po discover/org.kde.discover.packagekit.appdata.po
mkdir --parents `dirname kio/kio5` && mv frameworks/kio5.po kio/kio5.po
mkdir --parents `dirname plasma-desktop/plasma-desktop._desktop_` && mv kde-workspace/plasma-desktop._desktop_.po plasma-desktop/plasma-desktop._desktop_.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-settings` && mv kdenetwork/kdeconnect-settings.po kdeconnect-kde/kdeconnect-settings.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-kcm` && mv kdenetwork/kdeconnect-kcm.po kdeconnect-kde/kdeconnect-kcm.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-fileitemaction` && mv kdenetwork/kdeconnect-fileitemaction.po kdeconnect-kde/kdeconnect-fileitemaction.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-plugins` && mv kdenetwork/kdeconnect-plugins.po kdeconnect-kde/kdeconnect-plugins.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-indicator` && mv kdenetwork/kdeconnect-indicator.po kdeconnect-kde/kdeconnect-indicator.po
mkdir --parents `dirname kdeconnect-kde/org.kde.kdeconnect.kcm.appdata` && mv kdenetwork/org.kde.kdeconnect.kcm.appdata.po kdeconnect-kde/org.kde.kdeconnect.kcm.appdata.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-kio` && mv kdenetwork/kdeconnect-kio.po kdeconnect-kde/kdeconnect-kio.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-cli` && mv kdenetwork/kdeconnect-cli.po kdeconnect-kde/kdeconnect-cli.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-core` && mv kdenetwork/kdeconnect-core.po kdeconnect-kde/kdeconnect-core.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-kde._desktop_` && mv kdenetwork/kdeconnect-kde._desktop_.po kdeconnect-kde/kdeconnect-kde._desktop_.po
mkdir --parents `dirname kdeconnect-kde/plasma_applet_org.kde.kdeconnect` && mv kdenetwork/plasma_applet_org.kde.kdeconnect.po kdeconnect-kde/plasma_applet_org.kde.kdeconnect.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-interfaces` && mv kdenetwork/kdeconnect-interfaces.po kdeconnect-kde/kdeconnect-interfaces.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-app` && mv kdenetwork/kdeconnect-app.po kdeconnect-kde/kdeconnect-app.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-nautilus-extension` && mv kdenetwork/kdeconnect-nautilus-extension.po kdeconnect-kde/kdeconnect-nautilus-extension.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-urlhandler` && mv kdenetwork/kdeconnect-urlhandler.po kdeconnect-kde/kdeconnect-urlhandler.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-kded` && mv kdenetwork/kdeconnect-kded.po kdeconnect-kde/kdeconnect-kded.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-kde._json_` && mv kdenetwork/kdeconnect-kde._json_.po kdeconnect-kde/kdeconnect-kde._json_.po
mkdir --parents `dirname kdeconnect-kde/kdeconnect-sms` && mv kdenetwork/kdeconnect-sms.po kdeconnect-kde/kdeconnect-sms.po
mkdir --parents `dirname user-manager/user-manager._desktop_` && mv kde-workspace/user-manager._desktop_.po user-manager/user-manager._desktop_.po
mkdir --parents `dirname kscreenlocker/kscreenlocker._desktop_` && mv kde-workspace/kscreenlocker._desktop_.po kscreenlocker/kscreenlocker._desktop_.po
mkdir --parents `dirname powerdevil/powerdevil._desktop_` && mv kde-workspace/powerdevil._desktop_.po powerdevil/powerdevil._desktop_.po
mkdir --parents `dirname kscreen/kscreen._desktop_` && mv kde-workspace/kscreen._desktop_.po kscreen/kscreen._desktop_.po
